server:
  port: ${SERVER_PORT:8083}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  internal-services:
    tokens:
      user-service: ${USER_SERVICE_INTERNAL_TOKEN}
      restaurant-service: ${RESTAURANT_SERVICE_INTERNAL_TOKEN}
    self: ${ORDER_SERVICE_INTERNAL_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false