server:
  port: ${SERVER_PORT:8083}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/orderdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  internal-services:
    tokens:
      user-service: ${USER_SERVICE_INTERNAL_TOKEN:user-service-secret-token}
      restaurant-service: ${RESTAURANT_SERVICE_INTERNAL_TOKEN:restaurant-service-secret-token}
    self: ${USER_SERVICE_INTERNAL_TOKEN:order-service-secret-token}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
