server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/restaurantdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
