server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    database: ${REDIS_DB}

app:
  internal-services:
    tokens:
      user-service: ${USER_SERVICE_INTERNAL_TOKEN}
    self: ${USER_SERVICE_INTERNAL_TOKEN}
  verification:
    attempts:
      phone: ${PHONE_VERIFICATION_MAX_ATTEMPTS}
      email: ${EMAIL_VERIFICATION_MAX_ATTEMPTS}
  jwt:
    keys:
      private-key: ${JWT_PRIVATE_KEY}
      public-key: ${JWT_PUBLIC_KEY}
    expiration:
      access-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
      refresh-ms: ${JWT_REFRESH_EXPIRATION_MS:1296000000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always