server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/userdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}
    virtual-host: ${RABBITMQ_VHOST:/}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DB:0}

app:
  rabbitmq:
    exchanges:
      user-events:
        name: ${USER_EVENTS_EXCHANGE:user.events.exchange}
        type: direct
    queues:
      phone-verification:
        name: ${PHONE_VERIFICATION_QUEUE:phone.verification.queue}
        bindings:
          phone-verification-requested:
            exchange: user-events
            routing-key: ${PHONE_VERIFICATION_ROUTING_KEY:phone-verification-requested}

  redis:
    keys:
      signup-request:
        key: ${REDIS_KEY_SIGNUP_REQUEST:signup:request}
        ttl-ms: ${REDIS_TTL_SIGNUP_REQUEST:300000}
      phone-verification-code:
        key: ${REDIS_KEY_PHONE_VERIFICATION_CODE:phone:verification:code}
        ttl-ms: ${REDIS_TTL_PHONE_VERIFICATION_CODE:300000}
      phone-verification-rate-limit:
        key: ${REDIS_KEY_PHONE_VERIFICATION_RATE_LIMIT:phone:verification:rate-limit}
        ttl-ms: ${REDIS_TTL_PHONE_VERIFICATION_RATE_LIMIT:60000}
      phone-verification-attempts:
        key: ${REDIS_KEY_PHONE_VERIFICATION_ATTEMPTS:phone:verification:attempts}
        ttl-ms: ${REDIS_TTL_PHONE_VERIFICATION_ATTEMPTS:3600000}

  jwt:
    keys:
      private-key: ${JWT_PRIVATE_KEY:MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDNl7TBlOT6Rs9D77X9kuf4ZZNRiitj7OJZlNOGyxxweehH9arnUAAyUbpdBfCLT6Vtl74Y+u28j2KmpO+FuhHs6Nxf4JcWK5MzZK8bufLK4gJXh7qqe4RAPkChfYgAQZGQ9/TYZRmAcSm5jS406IEw1LQ3FpONPxDNIczg7DmCMwjbsLTUXyqBWwP9ha0kpCAlVMeJJWaVM/U3YczenzgYVh/uE+yEZWWUV2iS2xmq2gkycttVDVoy022k1ZE9eW9heJdYJ/9TXIzacmro0WWXpi5q9evz6KgL/N23uh7BsY5YKij0++BN2kwoRHvYsUdaDgbZKozsa6IsHNsfRqQpAgMBAAECggEAQcI+XJSlULAJZ29qxHqSm87Regk5q7J/C6wgpEKfDBLSCwI28dmS1oVxmINn1wdYoF8ivJa2J9Os+CRVQG6tgRtSMZCCguLZKF0R7UpisCXuHdUaDaGIQYwn2/9s2rgeOUI2HGjp6T1I3UKc/utHNzkxk1UzSMBdPV+MSn0EP/JD+/bHh+Vfe2oe3F1cKGCw0Qpa41rG/rppECL2yFEtYU4su4fnyeOP1RP2+7g6A7B1/tYx+vHkDXpEkxKbfQZX2Ry9T/eSb+kz8ZaIw5quBCkkR6DB4WjJf/MauewDL+UHMHaLpOl34MUJM4n8NwjsYhPEX8eCFlNqjTxr8AfnKQKBgQDwnD4ZH0HGTpwKyDsmQBILhhakvUoSf3qDoexi1KOa27881gRGhyt+S0b5+bVWf8vwQ3N/EoqmVqEEgJ+2kK66hJTCzvrYSq27un2UpJRS956T0PCWN4HENO/5r4YxlN10Fy/8ztVXjkZQTxgHY3vqXJPFD0u3Slc0YKlSNvCDpwKBgQDavhUwLgIduNhMinV8AJ/wgCKcEhuJtEA5ZjhXEcZlP5MgCdA/v3zCLQCOD8pE3ePlA6iqYca9JkADzz7JdbDUYMERa0sqgjPQSOMZmuGhLzhgJJJx66gLkh192V7s9Nfsj4HglZCBWDld6IXH23ZwXxph/IeW6U9CI5b8XBbTrwKBgDeLSgaQoaV+1iTjDkyJM+E3JhkHnYbhqM2kXqZ+Afqoyd/oY/pID/FKvWrNi2AZhmHDoHDwPdOiYe9hJf2GLt/d5V2HXH771llk9sKOr7LreM8Ux8VVsP4zXkacj3T4sZqwE6LfuH5K2M6HQ7vI6n0yu+Yc3tTEM5dizROunR03AoGADLu58gcLmn1TIgmBU0maBd7/pMQtFDQI9Q5tQyxGt0gfIWNQ2xUjhw4llR94L9AW3xL6c4ijkAk0+sPKrOGL/KDxPDlZs8zGhV5o0enBLqfYCUi3uaf1LU9BJj1MGFEcbKnh7pfmRJFFLaFGgF7XIy12FLQllHRaZ8g4ltIphgMCgYBlsK3xeaLOFtJ4ETgDnAxtCFx1gUgZ9S+EmjpYaVkAOxzO71gb4JvpdYU+jo8qmboNZy0zjAbklluWoWD+qof+fVXYdpqMsC2TuheARk95I/rz/coGFMy/9ueMtLmy6NrWoTBM8ZA4M5RRryCd6IjaFgNkXMxKH6jar6UIZpHHKA==}
      public-key: ${JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzZe0wZTk+kbPQ++1/ZLn+GWTUYorY+ziWZTThssccHnoR/Wq51AAMlG6XQXwi0+lbZe+GPrtvI9ipqTvhboR7OjcX+CXFiuTM2SvG7nyyuICV4e6qnuEQD5AoX2IAEGRkPf02GUZgHEpuY0uNOiBMNS0NxaTjT8QzSHM4Ow5gjMI27C01F8qgVsD/YWtJKQgJVTHiSVmlTP1N2HM3p84GFYf7hPshGVllFdoktsZqtoJMnLbVQ1aMtNtpNWRPXlvYXiXWCf/U1yM2nJq6NFll6YuavXr8+ioC/zdt7oewbGOWCoo9PvgTdpMKER72LFHWg4G2SqM7GuiLBzbH0akKQIDAQAB}
    expiration:
      access-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
      refresh-ms: ${JWT_REFRESH_EXPIRATION_MS:1296000000}

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
