server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}

app:
  internal-services:
    tokens:
      user-service: ${USER_SERVICE_INTERNAL_TOKEN}
    self: ${USER_SERVICE_INTERNAL_TOKEN}
  verification:
    attempts:
      phone: ${PHONE_VERIFICATION_MAX_ATTEMPTS}
      email: ${EMAIL_VERIFICATION_MAX_ATTEMPTS}
  address:
    limit: ${ADDRESS_LIMIT}
  jwt:
    keys:
      private-key: ${JWT_PRIVATE_KEY}
      public-key: ${JWT_PUBLIC_KEY}
    expiration:
      access-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
      refresh-ms: ${JWT_REFRESH_EXPIRATION_MS:1296000000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false