plugins {
    id 'java'
}

group = 'org.vovgoo'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.data:spring-data-commons:4.0.0'
    implementation 'org.springframework:spring-web:7.0.1'
    implementation 'org.hibernate.validator:hibernate-validator:9.0.1.Final'
    implementation 'com.googlecode.libphonenumber:libphonenumber:9.0.18'
    compileOnly 'org.projectlombok:lombok:1.18.38'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'
}

test {
    useJUnitPlatform()
}