spring:
  jackson:
    serialization:
      indent_output: true

jwt:
  secret: ${JWT_SECRET:defaultsecret}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}