server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false