allprojects {
    group = 'org.vovgoo'
    version = '0.0.1-SNAPSHOT'
}

description = 'food-delivery-platform'

repositories {
    mavenCentral()
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    repositories {
        mavenCentral()
    }

    dependencies {

    }
}
