version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  redis-user:
    image: redis:7-alpine
    container_name: redis-user
    ports:
      - "6379:6379"

  postgres-user:
    image: postgres:15-alpine
    container_name: postgres-user
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB_NAME}
      POSTGRES_USER: ${USER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
    ports:
      - "${POSTGRES_USER_PORT}:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  postgres-restaurant:
    image: postgres:15-alpine
    container_name: postgres-restaurant
    environment:
      POSTGRES_DB: ${RESTAURANT_SERVICE_DB_NAME}
      POSTGRES_USER: ${RESTAURANT_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${RESTAURANT_SERVICE_DB_PASSWORD}
    ports:
      - "${POSTGRES_RESTAURANT_PORT}:5432"
    volumes:
      - restaurant-db-data:/var/lib/postgresql/data

  postgres-order:
    image: postgres:15-alpine
    container_name: postgres-order
    environment:
      POSTGRES_DB: ${ORDER_SERVICE_DB_NAME}
      POSTGRES_USER: ${ORDER_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
    ports:
      - "${POSTGRES_ORDER_PORT}:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data

  user-service:
    container_name: user-service
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    ports:
      - "${USER_SERVICE_SERVER_PORT}:${USER_SERVICE_SERVER_PORT}"
    depends_on:
      - postgres-user
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${USER_SERVICE_SERVER_PORT}
      DB_URL: jdbc:postgresql://postgres-user:5432/${USER_SERVICE_DB_NAME}
      DB_USERNAME: ${USER_SERVICE_DB_USER}
      DB_PASSWORD: ${USER_SERVICE_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXPIRATION_MS: ${JWT_ACCESS_EXPIRATION_MS}
      JWT_REFRESH_EXPIRATION_MS: ${JWT_REFRESH_EXPIRATION_MS}

  restaurant-service:
    container_name: restaurant-service
    build:
      context: ./backend/restaurant-service
      dockerfile: Dockerfile
    ports:
      - "${RESTAURANT_SERVICE_SERVER_PORT}:${RESTAURANT_SERVICE_SERVER_PORT}"
    depends_on:
      - postgres-restaurant
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${RESTAURANT_SERVICE_SERVER_PORT}
      DB_URL: jdbc:postgresql://postgres-restaurant:5432/${RESTAURANT_SERVICE_DB_NAME}
      DB_USERNAME: ${RESTAURANT_SERVICE_DB_USER}
      DB_PASSWORD: ${RESTAURANT_SERVICE_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

  order-service:
    container_name: order-service
    build:
      context: ./backend/order-service
      dockerfile: Dockerfile
    ports:
      - "${ORDER_SERVICE_SERVER_PORT}:${ORDER_SERVICE_SERVER_PORT}"
    depends_on:
      - postgres-order
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${ORDER_SERVICE_SERVER_PORT}
      DB_URL: jdbc:postgresql://postgres-order:5432/${ORDER_SERVICE_DB_NAME}
      DB_USERNAME: ${ORDER_SERVICE_DB_USER}
      DB_PASSWORD: ${ORDER_SERVICE_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  user-db-data:
  restaurant-db-data:
  order-db-data: