version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - internal-user-service
      - internal-notification-service
    restart: on-failure

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "${MAILHOG_PORT}:8025"
    networks:
      - internal-notification-service
    restart: on-failure

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    networks:
      - internal-kafka
    restart: on-failure

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:${ZOOKEEPER_CLIENT_PORT}"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    networks:
      - internal-kafka
      - internal-notification-service
      - internal-order-service
    restart: on-failure

  postgres-user:
    image: postgres:15-alpine
    container_name: postgres-user
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - internal-user-service
    restart: on-failure

  postgres-restaurant:
    image: postgres:15-alpine
    container_name: postgres-restaurant
    environment:
      POSTGRES_DB: ${POSTGRES_RESTAURANT_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - restaurant-db-data:/var/lib/postgresql/data
    networks:
      - internal-restaurant-service
    restart: on-failure

  postgres-order:
    image: postgres:15-alpine
    container_name: postgres-order
    environment:
      POSTGRES_DB: ${POSTGRES_ORDER_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - internal-order-service
    restart: on-failure

  redis-user:
    image: redis:7-alpine
    container_name: redis-user
    networks:
      - internal-user-service
    restart: on-failure

  redis-api-gateway:
    image: redis:7-alpine
    container_name: redis-api-gateway
    networks:
      - internal-api-gateway
    restart: on-failure

  config-server:
    container_name: config-server
    build:
      context: .
      dockerfile: backend/config-server/Dockerfile
    environment:
      SERVER_PORT: ${CONFIG_SERVER_PORT}
      SPRING_PROFILES_ACTIVE: native
    volumes:
      - ./config-repo:/app/config-repo:ro
    networks:
      - internal-api-gateway
      - internal-user-service
      - internal-order-service
      - internal-restaurant-service
      - internal-notification-service
    restart: on-failure

  eureka-server:
    container_name: eureka-server
    build:
      context: .
      dockerfile: backend/eureka-server/Dockerfile
    environment:
      SERVER_PORT: ${EUREKA_SERVER_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - internal-api-gateway
      - internal-user-service
      - internal-order-service
      - internal-restaurant-service
    restart: on-failure

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: backend/api-gateway/Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:8080"
    depends_on:
      - eureka-server
      - config-server
      - redis-api-gateway
    environment:
      SERVER_PORT: ${API_GATEWAY_PORT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      REDIS_HOST: redis-api-gateway
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: 0
      FRONTEND_HOST: ${FRONTEND_HOST}
      EUREKA_SERVER_URL: http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
      CONFIG_SERVER_URL: http://config-server:${CONFIG_SERVER_PORT}/
    networks:
      - internal-api-gateway
    restart: on-failure

  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: backend/user-service/Dockerfile
    depends_on:
      - eureka-server
      - config-server
      - postgres-user
      - redis-user
      - rabbitmq
    environment:
      SERVER_PORT: ${USER_SERVICE_PORT}
      PREFER_IP_ADDRESS: false
      HOSTNAME: user-service
      DB_URL: jdbc:postgresql://postgres-user:5432/${POSTGRES_USER_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      REDIS_HOST: redis-user
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      USER_SERVICE_INTERNAL_TOKEN: ${USER_SERVICE_INTERNAL_TOKEN}
      PHONE_VERIFICATION_MAX_ATTEMPTS: ${PHONE_VERIFICATION_MAX_ATTEMPTS}
      EMAIL_VERIFICATION_MAX_ATTEMPTS: ${EMAIL_VERIFICATION_MAX_ATTEMPTS}
      ADDRESS_LIMIT: ${ADDRESS_LIMIT}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_ACCESS_EXPIRATION_MS: ${JWT_ACCESS_EXPIRATION_MS}
      JWT_REFRESH_EXPIRATION_MS: ${JWT_REFRESH_EXPIRATION_MS}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EUREKA_SERVER_URL: http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
      CONFIG_SERVER_URL: http://config-server:${CONFIG_SERVER_PORT}/
    networks:
      - internal-api-gateway
      - internal-user-service
    restart: on-failure

  restaurant-service:
    container_name: restaurant-service
    build:
      context: .
      dockerfile: backend/restaurant-service/Dockerfile
    depends_on:
      - eureka-server
      - config-server
      - postgres-restaurant
      - user-service
    environment:
      SERVER_PORT: ${RESTAURANT_SERVICE_PORT}
      PREFER_IP_ADDRESS: false
      HOSTNAME: restaurant-service
      DB_URL: jdbc:postgresql://postgres-restaurant:5432/${POSTGRES_RESTAURANT_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      USER_SERVICE_INTERNAL_TOKEN: ${USER_SERVICE_INTERNAL_TOKEN}
      RESTAURANT_SERVICE_INTERNAL_TOKEN: ${RESTAURANT_SERVICE_INTERNAL_TOKEN}
      IMGBB_API_KEY: ${IMGBB_API_KEY}
      IMGBB_ENDPOINT: ${IMGBB_ENDPOINT}
      RESTAURANT_IMAGE_LIMIT: ${RESTAURANT_IMAGE_LIMIT}
      DISH_IMAGE_LIMIT: ${DISH_IMAGE_LIMIT}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EUREKA_SERVER_URL: http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
      CONFIG_SERVER_URL: http://config-server:${CONFIG_SERVER_PORT}/
    networks:
      - internal-api-gateway
      - internal-restaurant-service
    restart: on-failure

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: backend/order-service/Dockerfile
    depends_on:
      - eureka-server
      - config-server
      - postgres-order
      - user-service
      - kafka
    environment:
      SERVER_PORT: ${ORDER_SERVICE_PORT}
      PREFER_IP_ADDRESS: false
      HOSTNAME: order-service
      DB_URL: jdbc:postgresql://postgres-order:5432/${POSTGRES_ORDER_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_URL: kafka:${KAFKA_PORT}
      USER_SERVICE_INTERNAL_TOKEN: ${USER_SERVICE_INTERNAL_TOKEN}
      RESTAURANT_SERVICE_INTERNAL_TOKEN: ${RESTAURANT_SERVICE_INTERNAL_TOKEN}
      ORDER_SERVICE_INTERNAL_TOKEN: ${ORDER_SERVICE_INTERNAL_TOKEN}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EUREKA_SERVER_URL: http://eureka-server:${EUREKA_SERVER_PORT}/eureka/
      CONFIG_SERVER_URL: http://config-server:${CONFIG_SERVER_PORT}/
    networks:
      - internal-api-gateway
      - internal-order-service
    restart: on-failure

  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: backend/notification-service/Dockerfile
    depends_on:
      - rabbitmq
      - kafka
    environment:
      SERVER_PORT: ${NOTIFICATION_SERVICE_PORT}
      KAFKA_URL: kafka:${KAFKA_PORT}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_VHOST: ${RABBITMQ_VHOST}
      SMTP_HOST: mailhog
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      FRONTEND_HOST: ${FRONTEND_HOST}
      FRONTEND_EMAIL_CHANGE_ROUTE: ${FRONTEND_EMAIL_CHANGE_ROUTE}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      CONFIG_SERVER_URL: http://config-server:${CONFIG_SERVER_PORT}/
    networks:
      - internal-notification-service
    restart: on-failure

networks:
  internal-user-service:
  internal-restaurant-service:
  internal-order-service:
  internal-notification-service:
  internal-api-gateway:
  internal-kafka:

volumes:
  user-db-data:
  restaurant-db-data:
  order-db-data: