rootProject.name = 'food-delivery-platform'

include 'backend:user-service'
include 'backend:restaurant-service'
include 'backend:order-service'
include 'backend:payment-service'
include 'backend:notification-service'
include 'backend:analytics-service'
include 'backend:api-gateway'
include 'backend:eureka-server'
include 'backend:config-server'