rootProject.name = 'food-delivery-platform'

include 'backend:common-domain'
include 'backend:common-security'
include 'backend:common-event'
include 'backend:common-client'
include 'backend:common-config'
include 'backend:user-service'
include 'backend:restaurant-service'
include 'backend:order-service'
include 'backend:notification-service'
include 'backend:api-gateway'
include 'backend:eureka-server'
include 'backend:config-server'