server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false