server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
        - id: user-service-addresses
          uri: lb://user-service
          predicates:
            - Path=/api/v1/address/**
        - id: user-service-docs
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - RewritePath=/user-service/v3/api-docs, /v3/api-docs

        - id: restaurant-service-restaurants
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/restaurants/**
        - id: restaurant-service-docs
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant-service/v3/api-docs
          filters:
            - RewritePath=/restaurant-service/v3/api-docs, /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /user-service/v3/api-docs
        name: User Service
      - url: /restaurant-service/v3/api-docs
        name: Restaurant Service

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always