spring:
  application:
    name: restaurant-service

  jackson:
    serialization:
      indent_output: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}