spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:./config-repo

server:
  port: ${PORT:8888}

logging:
  level:
    root: DEBUG
